### PR TITLE
fix/#70 calcFUV now checks the entire row

### LINKED ISSUE #70: Bug: calcFUV does not check entire row
- calcFUV breaks the check as soon as it finds a true value, but should check that the entire line is true

### PR DESCRIPTION
**Pull request by EdvinArdo**
fixes #70

### CODE REVIEW

**Review by johannaii — COMMENTED** [review]
Add a test case for this change, otherwise it looks good!

**Review by georgewbar — APPROVED** [review]
Looks good to me.

**Comment by georgewbar** [comment]
@johannaii @EdvinArdo sorry i did not see that you already left a comment

**Comment by georgewbar** [comment]
@EdvinArdo you can open a new pull request.

**Pull request merged**
