### PR TITLE
CMV 2.1, implemented functionality 4

### PR DESCRIPTION
**Pull request by Marcus9512**
The function checks if at least qpts points in the given input belong to
more then quads quadrants. The push also includes a test that test the
parameters given in the task and one custom alternativ where it exists
points in all 4 quadrants.

### CODE REVIEW

**Comment by EdvinArdo** [comment]
You need to resolve merge conflicts before pull request.

**Comment by Marcus9512** [comment]
Woops missed that part, the merge conflict is now resolved

**Review by EdvinArdo — CHANGES_REQUESTED** [review]
LIC 4 states "There exists at least one set of Q PTS _consecutive_ data points". The function lic4 does not test that the points are consecutive, but merely that they exist.

Additionally, lcm should be replaced with lic.

**Review by EdvinArdo — APPROVED** [review]
Lic 4 and test cases looks good. It returns false for undefined input parameters. I'd prefer it to either not take those conditions into account, or to throw an IllegalArgumentException, but it's a minor detail.

**Pull request merged**
